tests: improve error message for missing afl-* tools.
Before:

    RuntimeError: afl-cmin not found; is PATH set correctly?

After:

    RuntimeError: afl-cmin not found; is AFL installed?