tests/tools: fake $PWD so that is starts with ///.
This is needed to skip overzealous /tmp checks in afl-cmap.

Fixes:

    ======================================================================
    ERROR: tests.test_cmin.test
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/tmp/.../tests/test_cmin.py", line 68, in test
        b'1',
      File "/tmp/.../tests/test_cmin.py", line 51, in run_afl_cmin
        run(cmdline)
      File "/tmp/.../tests/tools.py", line 148, in run
        raise ipc.CalledProcessError(child.returncode, cmd[0])
    CalledProcessError: Command 'py-afl-cmin' returned non-zero exit status 1
    -------------------- >> begin captured stdout << ---------------------
    ...
    [-] Error: do not use this script in /tmp or /var/tmp.