setup: catch Cython import error.
Before:

    Traceback (most recent call last):
      File "setup.py", line 33, in <module>
        import Cython.Build
    ImportError: No module named Cython.Build

After:

    Traceback (most recent call last):
      File "setup.py", line 34, in <module>
        import Cython
    ImportError: No module named 'Cython'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "setup.py", line 36, in <module>
        raise RuntimeError('Cython >= 0.19 is required')
    RuntimeError: Cython >= 0.19 is required